apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trading-service
  name: trading-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-service
  strategy: {}
  template:
    metadata:
      labels:
        app: trading-service
    spec:
      containers:
      - image: ghcr.io/raf-si-2025/banka-4-backend/trading-service:latest
        name: trading-service
        resources: {}
        env:
        - name: ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: GRPC_PORT
          value: "50051"
        - name: JWT_SECRET
          value: your_jwt_secret_key
        - name: USER_SERVICE_ADDR
          value: "localhost:50051"
        - name: USER_SERVICE_BASE_URL
          value: http://localhost:8080
        - name: BANKING_SERVICE_ADDR
          value: "localhost:50052"
        - name: FINNHUB_API_KEY
          value: d715r3hr01ql6rg1fud0d715r3hr01ql6rg1fudg

        - name: DB_HOST
          value: db-primary.banka-4.svc
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: db-user
        - name: DB_PASS
          value: Pw0f6N8oCYG3ss2OWcP5g2WJ
        - name: DB_NAME
          value: "user-service-db"
        - name: DB_SSLMODE
          value: "prefer"

        - name: FRONTEND_BASE_URL
          value: http://localhost:5173
        - name: BACKEND_BASE_URL
          value: http://localhost:8080

        - name: EXCHANGE_RATE_API_KEY
          value: 1b2e6dbc86b61ad24e3458ea
        - name: TAX_ACCOUNT_NUMBER
          value: "444000000000000008"
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: trading-service
  labels:
    app: trading-service
  namespace: banka-4
spec:
  selector:
    app: trading-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080